<?php
namespace Kay\Bundle\TagBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{
    public function fetchAllName()
    {
        return $this->selectName()
            ->getQuery()
            ->getResult()
            ;
    }

    public function search($q)
    {
        return $this->selectName()
            ->where('t.name LIKE :search')
                ->setParameter('search', "%$q%")
            ->getQuery()
            ->getResult()
            ;
    }

    private function selectName()
    {
        return $this
            ->createQueryBuilder('t')
            ->select('t.name')
            ;
    }
}
