<?php
namespace Kay\Bundle\PlatformBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CoursesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoursesRepository extends EntityRepository
{
    public function getAll()
    {
        return $this->fetchAll()
            ->getQuery()
            ->getResult()
            ;
    }

    public function getByTag($tag_name)
    {
        return $this->fetchAll()
            ->join('c.tags', 't2')
            ->where('t2.name = :tag_name')
                ->setParameter('tag_name', $tag_name)
            ->getQuery()
            ->getResult()
            ;
    }

    private function fetchAll()
    {
        return $this->createQueryBuilder('c')
            ->join('c.tags', 't')
            ->select('c, t')
            ;
    }
}
