<?php

namespace Kay\Bundle\PlatformBundle\Repository;

/**
 * SubChapterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubChapterRepository extends \Doctrine\ORM\EntityRepository
{
}
